const SEARCH_PRODUCTS = "SEARCH_PRODUCTS";
const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";
const SORT_PRODUCTS = "SORT_PRODUCTS";
const UPDATE_PRICE_RANGE = "UPDATE_PRICE_RANGE";
const SORT_BY_RATING = "SORT_BY_RATING";
const FILTER_BY_SECTION = "FILTER_BY_SECTION";
const FILTER_BY_CATEGORY = "FILTER_BY_CATEGORY";
const CLEAR_FILTERS = "CLEAR_FILTERS";
export {
  SEARCH_PRODUCTS,
  UPDATE_PRODUCTS,
  SORT_PRODUCTS,
  UPDATE_PRICE_RANGE,
  SORT_BY_RATING,
  FILTER_BY_SECTION,
  FILTER_BY_CATEGORY,
  CLEAR_FILTERS,
};
